"""Prompts for paper summarization."""

from .summarizer import (
    SYSTEM_PROMPT,
    PAPER_INTRO_PROMPT,
    INNOVATION_PROMPT,
    TECHNIQUE_PROMPT,
    RESULTS_PROMPT,
    FINAL_SUMMARY_PROMPT,
    TITLE_AUTHORS_EXTRACT_PROMPT,
    MARKDOWN_FORMAT_CHECK_PROMPT,
    PROJECT_CONTEXT_PROMPT,
)

__all__ = [
    "SYSTEM_PROMPT",
    "PAPER_INTRO_PROMPT",
    "INNOVATION_PROMPT",
    "TECHNIQUE_PROMPT",
    "RESULTS_PROMPT",
    "FINAL_SUMMARY_PROMPT",
    "TITLE_AUTHORS_EXTRACT_PROMPT",
    "MARKDOWN_FORMAT_CHECK_PROMPT",
    "PROJECT_CONTEXT_PROMPT",
]
